// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAScr_2tUwoT2xRCCSuziIchT0u-ZwXgy8',
    appId: '1:114079870033:web:bd8766216f9301914a5c70',
    messagingSenderId: '114079870033',
    projectId: 'dolittle-vet',
    authDomain: 'dolittle-vet.firebaseapp.com',
    storageBucket: 'dolittle-vet.appspot.com',
    measurementId: 'G-B3E7J1QGD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfUafrnkwoj6BzaRBK1q05WzmSVgye4SY',
    appId: '1:114079870033:android:b6820546b58607ec4a5c70',
    messagingSenderId: '114079870033',
    projectId: 'dolittle-vet',
    storageBucket: 'dolittle-vet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD6RllbwqxlnRMfVynXP7628opu8mo-Zs',
    appId: '1:114079870033:ios:b0b196b6637203b84a5c70',
    messagingSenderId: '114079870033',
    projectId: 'dolittle-vet',
    storageBucket: 'dolittle-vet.appspot.com',
    androidClientId: '114079870033-eoll4t4b34d16gad6ntrtevdmvpqnc7m.apps.googleusercontent.com',
    iosClientId: '114079870033-sqoajr7v8d17csmsc9p0r3764hmluiqd.apps.googleusercontent.com',
    iosBundleId: 'kr.zentry.dolittleforveterinarian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD6RllbwqxlnRMfVynXP7628opu8mo-Zs',
    appId: '1:114079870033:ios:bc847e3b9b6d11ca4a5c70',
    messagingSenderId: '114079870033',
    projectId: 'dolittle-vet',
    storageBucket: 'dolittle-vet.appspot.com',
    androidClientId: '114079870033-eoll4t4b34d16gad6ntrtevdmvpqnc7m.apps.googleusercontent.com',
    iosClientId: '114079870033-quboau6gleedsjvd6irdl324glf2e3li.apps.googleusercontent.com',
    iosBundleId: 'com.example.dolittleForVet',
  );
}
